#username=id:username
#password=id:password
#submit=id:submit
#post-title=css:.post-title



# URLs
login_url=https://www.saucedemo.com/
products_url=https://www.saucedemo.com/inventory.html

# Login Page Locators
login_username_id=id:user-name
login_password_id=id:password
login_button_id=id:login-button
welcome_message_id=className:inventory_list

# Add Product Locators 
add_product_link_id=id:add-to-cart-sauce-labs-backpack